# NYC Data Cleaning

## Import Libs

In [4]:
import pandas as pd
import numpy as np

## Import Data

In [5]:
df_trips = pd.read_csv("datasets/yellow_tripdata_2024_01.csv")
df_zones = pd.read_csv('datasets/taxi_zone_lookup.csv')
df_weather = pd.read_csv('datasets/weather_data.csv')
display(df_trips.head(2))
display(df_zones.head(2))
display(df_weather.head(2))

/var/folders/k5/sy4g3yjd3gl3g9vbx7cjw3z00000gn/T/ipykernel_30930/3946931742.py:1: DtypeWarning: Columns (3,5,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_trips = pd.read_csv("datasets/yellow_tripdata_2024_01.csv")

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-13 03:18:09.000000,2024-01-13 03:24:37.000000,1,2.31,1,N,48,68,1,11.4,1.0,0.5,3.28,0.0,1.0,19.68,2.5,0.0
1,2,2024-01-13 03:52:58.000000,2024-01-13 04:01:18.000000,1,2.61,1,N,231,164,1,13.5,1.0,0.5,2.00,0.0,1.0,20.50,2.5,0.0

   LocationID Borough            Zone service_zone
0           1     EWR  Newark Airport          EWR
1           2  Queens     Jamaica Bay    Boro Zone

,year,month,day,hour,temp,temp_source,rhum,rhum_source,prcp,prcp_source,...,wpgt,wpgt_source,pres,pres_source,tsun,tsun_source,cldc,cldc_source,coco,coco_source
0,2024,1,1,0,7.0,dwd_hourly,79,dwd_hourly,0.0,dwd_hourly,...,32.0,dwd_poi,1006.4,dwd_hourly,0,dwd_poi,8.0,dwd_hourly,8,dwd_hourly
1,2024,1,1,1,6.9,dwd_hourly,78,dwd_hourly,0.0,dwd_hourly,...,33.0,dwd_poi,1006.6,dwd_hourly,0,dwd_poi,8.0,dwd_hourly,7,dwd_poi

## Check Table Info

In [6]:
print("SHAPE------------------------------------------------------")
print(f"df_trips: {df_trips.shape}\n\n\n")
print(f"df_zones: {df_zones.shape}\n\n\n")
print(f"df_weather: {df_weather.shape}\n\n\n")

print("DUPLICATE COUNT------------------------------------------------------")
print(f"df_trips: {df_trips.duplicated().sum()}\n\n\n")
print(f"df_zones: {df_zones.duplicated().sum()}\n\n\n")
print(f"df_weather: {df_weather.duplicated().sum()}\n\n\n")

print("INFO------------------------------------------------------")
print(f"df_trips: {df_trips.info()}\n\n\n")
print(f"df_zones: {df_zones.info()}\n\n\n")
print(f"df_weather: {df_weather.info()}\n\n\n")

SHAPE------------------------------------------------------
df_trips: (2964624, 19)



df_zones: (265, 4)



df_weather: (8784, 26)



DUPLICATE COUNT------------------------------------------------------
df_trips: 0



df_zones: 0



df_weather: 0



INFO------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   object
 2   tpep_dropoff_datetime  object
 3   passenger_count        object
 4   trip_distance          float64
 5   RatecodeID             object
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   object
 18  Airport_fee            object
dtypes: float64(8), int64(4), object(7)
memory usage: 429.7+ MB
df_trips: None



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       264 non-null    object
 2   Zone          264 non-null    object
 3   service_zone  263 non-null    object
dtypes: int64(1), object(3)
memory usage: 8.4+ KB
df_zones: None



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         8784 non-null   int64
 1   month        8784 non-null   int64
 2   day          8784 non-null   int64
 3   hour         8784 non-null   int64
 4   temp         8784 non-null   float64
 5   temp_source  8784 non-null   object
 6   rhum         8784 non-null   int64
 7   rhum_source  8784 non-null   object
 8   prcp         8784 non-null   float64
 9   prcp_source  8784 non-null   object
 10  snwd         7820 non-null   float64
 11  snwd_source  7820 non-null   object
 12  wdir         8784 non-null   int64
 13  wdir_source  8784 non-null   object
 14  wspd         8784 non-null   float64
 15  wspd_source  8784 non-null   object
 16  wpgt         8784 non-null   float64
 17  wpgt_source  8784 non-null   object
 18  pres         8784 non-null   float64
 19  pres_source  8784 non-null   object
 20  tsun         8784 non-null   int64
 21  tsun_source  8784 non-null   object
 22  cldc         8783 non-null   float64
 23  cldc_source  8784 non-null   object
 24  coco         8784 non-null   int64
 25  coco_source  8784 non-null   object
dtypes: float64(7), int64(8), object(11)
memory usage: 1.7+ MB
df_weather: None

## Drop Duplicate Rows

In [7]:
df_trips.drop_duplicates(inplace=True)
df_trips.shape

(2964624, 19)

## Check Missing Values

In [8]:
df_trips.isna().mean().round(4) * 100

VendorID                 0.0
tpep_pickup_datetime     0.0
tpep_dropoff_datetime    0.0
passenger_count          0.0
trip_distance            0.0
RatecodeID               0.0
store_and_fwd_flag       0.0
PULocationID             0.0
DOLocationID             0.0
payment_type             0.0
fare_amount              0.0
extra                    0.0
mta_tax                  0.0
tip_amount               0.0
tolls_amount             0.0
improvement_surcharge    0.0
total_amount             0.0
congestion_surcharge     0.0
Airport_fee              0.0
dtype: float64

## Handle Numeric Columns

In [9]:
num_cols = [3, 4, 5, 17, 18]
c = df_trips.columns[num_cols]

# 1) Trim only where values are strings (works with mixed-type object columns)
df_trips[c] = df_trips[c].map(lambda x: x.strip() if isinstance(x, str) else x)

# 2) Remove common non-numeric artifacts and normalize negatives in parentheses
df_trips[c] = (df_trips[c]
    .replace({'\u00A0': ' ', ',': '', r'\$': '', '%': ''}, regex=True)  # nbsp, commas, $, %
    .replace(r'^\((.*)\)$', r'-\1', regex=True)                         # (123) -> -123
    .replace({'': pd.NA, 'nan': pd.NA, '—': pd.NA, '–': pd.NA})         # blanks/dashes -> NA
)

# 3) Convert to numeric; anything unparseable becomes NaN/<NA>
df_trips[c] = df_trips[c].apply(pd.to_numeric, errors='coerce')

# 4) Use pandas' nullable dtypes so columns don't fall back to object
df_trips[c] = df_trips[c].convert_dtypes()

df_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   object
 2   tpep_dropoff_datetime  object
 3   passenger_count        Int64
 4   trip_distance          Float64
 5   RatecodeID             Int64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   Float64
 18  Airport_fee            Float64
dtypes: Float64(3), Int64(2), float64(7), int64(4), object(3)
memory usage: 443.9+ MB

In [10]:
df_trips.select_dtypes(include=np.number).columns.tolist()

['VendorID',
 'passenger_count',
 'trip_distance',
 'RatecodeID',
 'PULocationID',
 'DOLocationID',
 'payment_type',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'improvement_surcharge',
 'total_amount',
 'congestion_surcharge',
 'Airport_fee']

## Handle Date Time Columns

In [11]:
date_cols = [1, 2]
c = df_trips.columns[date_cols]

df_trips[c] = df_trips[c].apply(lambda c : pd.to_datetime(c, errors="coerce", utc=True))  # or .dt.tz_convert("Asia/Singapore")

df_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[ns, UTC]
 2   tpep_dropoff_datetime  datetime64[ns, UTC]
 3   passenger_count        Int64
 4   trip_distance          Float64
 5   RatecodeID             Int64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   Float64
 18  Airport_fee            Float64
dtypes: Float64(3), Int64(2), datetime64[ns, UTC](2), float64(7), int64(4), object(1)
memory usage: 443.9+ MB

In [12]:
df_trips.select_dtypes(include=['datetime', 'datetimetz']).columns.tolist()

['tpep_pickup_datetime', 'tpep_dropoff_datetime']

## Handle Categorical Columns

In [13]:
df_trips["store_and_fwd_flag"].unique()

array(['N', 'Y', '\\N'], dtype=object)

In [14]:
c = df_trips.select_dtypes(include=['object']).columns

def norm(c):
    return (
    c.astype("string")               # keeps NA as <NA>, not "nan"
     .str.replace("—", "-", regex=False)
     .str.replace("–", "-", regex=False)
     .str.replace("\u00A0", " ", regex=False)
     .str.replace(r"\\N", "N", regex=True)
     .str.strip()
)

df_trips[c] = df_trips[c].apply(norm)

df_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[ns, UTC]
 2   tpep_dropoff_datetime  datetime64[ns, UTC]
 3   passenger_count        Int64
 4   trip_distance          Float64
 5   RatecodeID             Int64
 6   store_and_fwd_flag     string
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   Float64
 18  Airport_fee            Float64
dtypes: Float64(3), Int64(2), datetime64[ns, UTC](2), float64(7), int64(4), string(1)
memory usage: 443.9 MB

In [15]:
display(df_trips.select_dtypes(include=['object']).columns.tolist())

[]

In [16]:
df_trips["store_and_fwd_flag"].unique()

<StringArray>
['N', 'Y']
Length: 2, dtype: string

## Merge Tables

In [17]:
# Join df_trips + df_zones
df_trips = df_trips.merge(df_zones, left_on='PULocationID', right_on='LocationID', how='left')

In [18]:
# Truncate to hour
df_trips['hour'] = pd.to_datetime(df_trips['tpep_pickup_datetime']).dt.hour
df_trips.head(2)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,LocationID,Borough,Zone,service_zone,hour
0,2,2024-01-13 03:18:09+00:00,2024-01-13 03:24:37+00:00,1,2.31,1,N,48,68,1,...,0.0,1.0,19.68,2.5,0.0,48,Manhattan,Clinton East,Yellow Zone,3
1,2,2024-01-13 03:52:58+00:00,2024-01-13 04:01:18+00:00,1,2.61,1,N,231,164,1,...,0.0,1.0,20.50,2.5,0.0,231,Manhattan,TriBeCa/Civic Center,Yellow Zone,3

In [ ]:
# Join with df_weather
df_trips = df_trips.merge(df_weather, on='hour', how='left')
df_trips.head(3)

## Export Data

In [ ]:
df_trips.to_csv('datasets/trips_complete.csv', index=False)
print("Done")